repos:
    - repo: local
      hooks:
          - id: stylua
            name: format lua with stylua
            language: system
            entry: stylua.exe --config-path "C:\Users\Neel\.stylua.toml"
            files: \.lua$
